# fly.toml app configuration file generated for quallab on 2023-09-11T15:17:55+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quallab"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
